#!/usr/bin/env bash
# Install nginx

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx Https'
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart
