#!/usr/bin/env bash
# Install nginx
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx Https'
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/rewrite/a  error_page 404 /error404.html;' /etc/nginx/sites-enabled/default
service nginx restart
